root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/app.exe ./cmd/web/main.go"
bin = "tmp/app.exe"

# Files to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]
# Directories to exclude
exclude_dir = ["tmp", "vendor"]
# Recursively watch directories
follow_symlink = true
# Delay between file change checks (in milliseconds)
delay = 1000
# Prevent launching multiple instances
stop_on_error = true
# Kill process before rebuilding
kill_delay = "0s"

[log]
# Show date/time in logs
time = true
level = "warn"

[color]
# Optional color customization
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

# Crucial setting to stop the previous process
[screen]
clear_on_rebuild = true

# This section defines how the process will be terminated
[misc]
# Send SIGTERM to the current process before starting a new one
clean_on_exit = true
